# File: .github/workflows/main.yml

name: CI_Eksperimen_SML_Mayang-Gumelar

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  CSV_URL: "preprocessing/Data_Liver_Cleaned.csv"
  TARGET_VAR: "Target"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout Repository
      uses: actions/checkout@v3

    - name: 2. Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Check Env
      run: |
        echo %CSV_URL

    - name: 3. Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 4. Run Preprocessing Script
      run: |
        python /preprocessing/automate_Mayang-Gumelar.py

    - name: 5. Verify Output Files
      run: |
        echo "Verifying Preprocessing Outputs..."
        # Cek nama file sesuai output_prefix='Liver' dan scaler_save_path='RobustScaler.joblib'
        test -f Liver_train.csv
        test -f Liver_test.csv
        test -f RobustScaler.joblib
        # Hapus verifikasi model training karena fungsi tersebut belum diimplementasikan di skrip Anda.